### ISSUE TITLE
[Feature request] Add dpy support for EmbedCreator

### ISSUE THREAD

**Issue by J-Daniel-1** [flaree/Flare-Cogs#100]
Hey Flare, I was wondering if its possible for you to add d.py support for your embedcreator cog. If it would too much for that cog, maybe a separate cog? 

Alternatively, if you don't have time or wish to not spend time on this, was wondering if I was to have your approval to creating a bounty cog for a d.py embed cog that similarly setup to yours in terms of command names? I don't want to request something that is almost an exact copy of your command setup for the cog without you knowing.

**Comment by jack1142** [comment]
I'm not flare, but what do you mean by "d.py support"?

**Comment by J-Daniel-1** [comment]
> 
> 
> I'm not flare, but what do you mean by "d.py support"?

Using python instead of json. ref: https://cog-creators.github.io/discord-embed-sandbox/

**Comment by flaree** [comment]
There'd be no difference to using eval then, I don't see a reason to do
that and open up malicious features

>

**Comment by flaree** [comment]
There's no way I can limit it to just discord embed code, it'll just be a
python eval/repl and that has its flaws as that's why it's locked behind a
flag

**Comment by J-Daniel-1** [comment]
I didn't know using Python to create embeds, through a cog, could open up malicious features. I was gonna use this to touch the python coding and learning how it words but I guess not. Thanks for the info.
