### ISSUE TITLE
[Feature Request] EmbedCreator

### ISSUE THREAD

**Issue by Merp-Me** [flaree/flare-cogs#105]
Hi, I was wondering whether you would be interested in adding the ability to specify the channel where the embed will be posted when sending an embed. For example, if you are in a large server and want to send an announcement, you could run the "[p]embed json #announcement (json code)" in a botcommands channel
This would post the announcement in that channel without having to send the command in that channel.

**Comment by flaree** [comment]
This was intentionally not added as it messed up while using json due to
the "". I could not find a way to make it work
