### ISSUE TITLE
[Unbelievaboat] Addmoneyrole not working

### ISSUE THREAD

**Issue by Zenchaeus** [flaree/flare-cogs#109]
**Describe the bug**
I tried the addmoneyrole from unbelievaboat because i was going to add money to all members in a specific role. when i use the command, a checkmark reaction appears, but when i try to check the balance either wallet or bank, the value doesn't change at all.

**Output of [p]help CogName and [p]debuginfo**

DEBUGINFO
Debug Info for Red
Red version
3.4.7
Python version
3.8.7 (64bit)
Discord.py version
1.6.0
Pip version
21.0.1
System arch
x86_64
User
mkurisu069
Storage type
JSON
Disabled intents
None
OS version
Ubuntu 18.04
Python executable
/home/mkurisu069/redenv/bin/python
Data path
/home/mkurisu069/.local/share/Red-DiscordBot/data/Redbot
Metadata file
/home/mkurisu069/.config/Red-DiscordBot/config.json

HELP
Unbelievaboat Commands.
Cog Version: 0.5.7
​
Commands:
addmoneyrole Add money to the balance of all users within a role.
cooldowns List your remaining cooldowns..
crime Commit a crime, more risk but higher payout.
deposit Deposit cash from your wallet to your bank.
removemoneyrole Remove money from the bank balance of all users...
rob Rob another user.
rouletteset Manage settings for roulette.
unbset Manage various settings for Unbelievaboat.
wallet Wallet commands.
Commands: (continued)
withdraw Withdraw cash from your bank to your wallet.
work Work for some cash.
Type !help <command> for more info on a command. You can also type !help <category> for more info on a category.

**Comment by flaree** [comment]
I cannot replicate your issue, it works as intended on multiple bots.

**Comment by Zenchaeus** [comment]
![Screenshot_20210405_185829_com discord](https://user-images.githubusercontent.com/67543490/113567437-328bde80-9641-11eb-88d2-e664d362eb5d.png)
as you can see here, i tried again to verify again if it worked or not. but it still doesn't. be it the bank or the wallet

**Comment by flaree** [comment]
I've added two debug logs, launch the bot with --debug and try again. Any errors will be printed in the console.

**Comment by Zenchaeus** [comment]
> I've added two debug logs, launch the bot with --debug and try again. Any errors will be printed in the console.

i'm kinda noob to linux stuff. i don't know how to do that lol. any specific steps?

**Comment by flaree** [comment]
Launch the bot with the --debug flag. Google flags if you don't know what
they are cause I will not assist in that regard. The only way it can fail
is if the amount is not an integer or so.


I've tried in 5 different bots all with different setups and all work as
intended.

**Comment by Zenchaeus** [comment]
any other way i can fix it? i tried uninstalling but didn't work

**Comment by flaree** [comment]
The problem is something on your end.

Either nobody is in that role or your bot isn't picking up role members and
I cannot do anything about that.

**Comment by Zenchaeus** [comment]
> The problem is something on your end. Either nobody is in that role or your bot isn't picking up role members and I cannot do anything about that.

that's too bad. i guess i can close this now
