### ISSUE TITLE
If Forward DM message contains regular text + embed, it breaks as embed is being used by Forward.

### ISSUE THREAD

**Issue by Skyridr** [flaree/flare-cogs#128]
Here's what happens if I use Warden Defender to send a DM to a user in regular text + embed form. This is the DM that is being received by the user:

![image](https://user-images.githubusercontent.com/6794064/127661884-4683fd36-0071-4d56-a3c2-05167adb8137.png)

And this is what Forward sends:

![image](https://user-images.githubusercontent.com/6794064/127662220-166e831f-1db7-4cfa-9670-eda2a68ab6bd.png)

Apparently only the embed part was being send out, but not the regular text.

**Comment by flaree** [comment]
Should be fixed in 137dd71bd8fadc9f0fb34f7bf062dedcd6eed30c, let me know if theres any problems.
