### ISSUE TITLE
[RedditPost] Plugin doesn't work anymore

### ISSUE THREAD

**Issue by botflakes** [flaree/flare-cogs#129]
Hey,

first and foremost thanks for the work you put into your plugins! But unfortunately I'll have a problem to get it running again.
It was working for months without a problem but now it doesn't work anymore. 

I use it on the r/ASRock Discord for getting the latest posts of the subreddit into specified channel. I already reinstalled it but everytime I try to use this command "!redditpost add ASRock subreddit-posts" the bot comes back with this massage "Please ensure the subreddit name is correct." - So I did and thought maybe trying it all lower case but same story. Also tried it with a different subreddit (AMD) also no dice.

Here's the outcome of "!help redditpost"

![BspQ24](https://user-images.githubusercontent.com/69024038/134380735-40279c76-bd41-435d-8692-7f0fa7107f8e.png)

and here the outcome of debuginfo

# Debug Info for Red:

## System Metadata:
CPU Cores: 6 (x86_64)
RAM: 1000.1MB/15.6GB (7.9%)

## OS Variables:
OS version: Ubuntu 20.04
User: redbot
Python executable: /home/redbot/redenv/bin/python
Python version: 3.8.10 (64bit)
Pip version: 21.2.4
Red version: 3.4.13
Discord.py version: 1.7.3

## Red variables:
Instance name: redbot
Owner(s): 128184564915896320 (CornFlakes#7703)
Storage type: JSON
Disabled intents: None
Data path: /home/redbot/.local/share/Red-DiscordBot/data/redbot
Metadata file: /home/redbot/.config/Red-DiscordBot/config.json

**Comment by flaree** [comment]
Unfortunately due to Reddit changing the API this cog is no longer working at all and will need considerable changing in order to be fixed. I do have plans to eventually get this done but there's no time line.

**Comment by botflakes** [comment]
Ah I see. Okay, thanks for the replay regardless!
