### ISSUE TITLE
[FACEIT] 404 on match room 

### ISSUE THREAD

**Issue by Ufinexa** [flaree/flare-cogs#130]
**Describe the bug**
Opening the match room link in most recent matches returns a 404

Link it gave - https://www.faceit.com/%7Blang%7D/csgo/room/1-774a7cbb-8361-4b2f-a609-ac0649ca872d
Match room link - https://www.faceit.com/en/csgo/room/1-774a7cbb-8361-4b2f-a609-ac0649ca872d/scoreboard

Looks like it's trying to figure out the language of the site to load it in and not finding it? I'm not sure though

**Comment by flaree** [comment]
Which command exactly was this?

**Comment by Ufinexa** [comment]
I did "!faceit profile" for my profile and then clicked the swords react for most recent matches, went to look at my recent match and that was the match room link that came out

**Comment by flaree** [comment]
I've still not been able to repo this, I'll have another look over the weekend

**Comment by flaree** [comment]
fixed in cfe685e
apologies
