### ISSUE TITLE
[F1] Schedule embed footer is misleading

### ISSUE THREAD

**Issue by WreckRox** [flaree/flare-cogs#137]
**Describe the bug**
The footer in the embed when you do `[p]f1 schedule` says `Times displayed are in UTC.` but this is incorrect as the times are now local times thanks to timestamps introduced in f0bfe4d 

**Output of [p]help CogName and [p]debuginfo**
[Output of help](https://media.discordapp.net/attachments/133251234164375552/909147330417143888/unknown.png)
[Output of debuginfo](https://media.discordapp.net/attachments/133251234164375552/909147812833411102/unknown.png)

**Comment by flaree** [comment]
Fixed in 45aa64c
