### ISSUE TITLE
[Feature Requests][Giveaways]Ability to set start/end time and date

### ISSUE THREAD

**Issue by MayhemBill** [flaree/flare-cogs#143]
as title says, I would like to be able to set either a start or end time and date, so I could more accurately run giveaways (we run them weekly on our discord and would like to start using the bot). It tends to be a bit of an issue trying to time them correctly to end the way we would like them to.

**Comment by MayhemBill** [comment]
going to close since I'm going to go with a different cog

**Comment by flaree** [comment]
Regardless of using another cog im still interested in this. Do you propose
having like an --enddate flag where you can pass an exact date of

**Comment by MayhemBill** [comment]
That would probably be the easiest way of doing so, instead of making it a default feature

**Comment by flaree** [comment]
Thanks, added in latest commit.
