### ISSUE TITLE
Verify process in dms instead of the channel - EmailVerify

### ISSUE THREAD

**Issue by XenonUnity** [flaree/flare-cogs#149]
**Describe the feature you'd like**
From a privacy perspective I think it would be better if the verification process happens in the bots dms instead of a channel. This would reduce or remove the risk of leaking your own email to other users - although this could also be solved by having a write access only channel with read permissions denied.

**Comment by flaree** [comment]
This is how it initially is on my CASE repo however as this allows for multiple servers there is no easy way to do this.

**Comment by XenonUnity** [comment]
Oh... I guess the only real way to somewhat do it is the write only access to a channel?

**Comment by flaree** [comment]
I will have it delete the message if it can, but this won't be until I'm
home on Sunday.

**Comment by flaree** [comment]
It now deletes the invoking message
