### ISSUE TITLE
Roulette crash bug

### ISSUE THREAD

**Issue by BUYDRUGS** [flaree/flare-cogs#156]
I'm running your unbelievaboat - roulette on my server. The wheel tends to get stuck on "the wheel is spinning" if people place single number bets between 1-36. zero seems to be exempt from this bug. the result never comes out and you can't start a new spin until you restart the bot or unload/load unbelievaboat again

**Comment by BUYDRUGS** [comment]
Also the same error seems to happen when you place a bet while the wheel is spinning 
![image](https://user-images.githubusercontent.com/77588396/158901449-f126e4d8-6643-4db1-9cb4-6de096d8c22e.png)
and the result never comes out, can't start next spin til bot is restarted

**Comment by flaree** [comment]
I cannot replicate this on my bots or other people's bots. If there is any
error shown in the logs then please post it.

Also edit your issue to use the format otherwise I have no clue what you're
running to get such issue.
