### ISSUE TITLE
[Ignore Mentions and Timestamps] [Highlight]

### ISSUE THREAD

**Issue by Ibotmealot** [flaree/flare-cogs#158]
**Describe the feature you'd like**
Currently I have a highlight setup for my user id, however, when someone mentions you the cog sees the ID in the mention and still sends you the highlight. What I am wanting is that if a user is running a command but with my ID (no mention) the bot picks this up, and just ignores mentions containing your ID. I hope that makes sense lol. Additionally, showing the timestamps of the messages in the highlight message would be amazing. I'll attach an example image. 
**Additional context**
No other additional information. 
![image](https://user-images.githubusercontent.com/42391199/161651470-73298401-c7c6-4c85-b4c9-b2a29dc4a81e.png)

**Comment by flaree** [comment]
Turn on boundaries for the ID and mentions won't highlight
