### ISSUE TITLE
Crypto cog delay

### ISSUE THREAD

**Issue by BUYDRUGS** [flaree/flare-cogs#165]
The crypto cog has a delay because of the CMC api giving delayed prices, thus users can scalp while knowing what the future price will be. it scales really fast with large numbers, easily hitting max balance after a number of days

I think in order to fix this, when placing a buy or sell order with the crypto cog, it needs to execute in 1-2minutes with the new price.

**Comment by flaree** [comment]
Fixed some time ago.

**Comment by flaree** [comment]
Unfortunately I have no desire or will to add this to the cog. The cog was just a crypto port of Stocks and will remain that way. However, I will accept PRs from people should they implement it themself.
