### ISSUE TITLE
[BUG] Exception when user with DM's disabled tries to enter giveaway and doesn't meet requirements

### ISSUE THREAD

**Issue by DJTOMATO** [flaree/flare-cogs#170]
**Describe the bug**
https://cdn.discordapp.com/attachments/736337036067209216/986799851331260497/unknown.png
Exception when user with DM's disabled tries to enter giveaway and doesn't meet requirements

**Output of [p]help CogName and [p]debuginfo**
https://bae.lena.moe/o4hzlm4pbjxc.png
https://bae.lena.moe/3v8i898i3y3w.png

**Comment by flaree** [comment]
Fixed in 0d32b576e1
