### ISSUE TITLE
[FEATURE] [Giveaway] Add image via argument

### ISSUE THREAD

**Issue by DJTOMATO** [flaree/flare-cogs#171]
**Describe the feature you'd like**
``--image url`` will show image as part of the embed.

**Additional context**
https://bae.lena.moe/x2lnavw7u5en.png

**Comment by flaree** [comment]
Thanks for the feature request! I am currently on a much needed break from all coding activities so this may sit in the backlog for a few weeks until my motivation or desire to code returns.

If anyone else would like to tackle this in the meantime, it is quite trivial and I can offer some assistance in my support channel if needed

**Comment by flaree** [comment]
Added in 383131
