### ISSUE TITLE
[FEATURE] [FORWARD]

### ISSUE THREAD

**Issue by Dragonias** [flaree/flare-cogs#172]
**Describe the feature you'd like**
I would like to be able to toggle the abilty to see who my Bot direct messages while yes it shows it direct messages someone it doesnt say who.. Theres sometimes people that use features for ill intend and I'd like to see who they are.

**Additional context**
Can't really attach any screenshots here for why this would be needed as some of it is TOS breaking.

**Comment by flaree** [comment]
I'm sorry, I don't quite understand what you mean. Can you clarify it further?

**Comment by Dragonias** [comment]
A good example would be this where it sent a message to someone that was spamming a command but I cant figure out who it was due to the Forward cog not saying who it messaged. 
![Bild_2022-06-18_024602971](https://user-images.githubusercontent.com/69013741/174415645-2d65640e-68cb-49aa-ac37-9b5571b09190.png)

**Comment by flaree** [comment]
Ah I'll try something when I return to coding. Feel free to make a PR in
the meantime if you're capable as I won't be around for another month or
so.

**Comment by flaree** [comment]
Fixed in 41df7353d
