### ISSUE TITLE
[FEATURE] [COG] Enable [p]highlight for embedded messages

### ISSUE THREAD

**Issue by mizz141** [flaree/flare-cogs#174]
**Describe the feature you'd like**
I'd like for [p]highlight to notify the user on messages, even if they are being used in embeds, ideally this would be a feature which would need to be enabled with the "Syntax: [p]highlight bots <state> [channel] [word]" command

**Comment by flaree** [comment]
Added in 406b7d0

Untested, please report any issues.

**Comment by mizz141** [comment]
Thanks for the Implementation, however when the embed triggers a highlight, The embed shows as "No Content" inside the DM received.
![Screenshot 2022-07-10 093115](https://user-images.githubusercontent.com/20839616/178135539-6274dba0-dfe2-4714-b150-4aef9f4d4b24.jpg)

**Comment by flaree** [comment]
This is intended
