### ISSUE TITLE
[FEATURE] [redditpost] Optionally publish posts in announcement channels

### ISSUE THREAD

**Issue by tigattack** [flaree/flare-cogs#185]
**Describe the feature you'd like**

It'd be great to have the option to [publish](https://discordpy.readthedocs.io/en/v1.7.3/api.html#discord.Message.publish) posts made in an announcement channel with the redditpost cog.

**Additional context**

None.

**Comment by flaree** [comment]
I'll implement this once Red 3.5 is released, all my cogs are currently feature locked until they support the next release.

**Comment by tigattack** [comment]
No problem, thanks!

**Comment by flaree** [comment]
Added in latest commit, thanks for the suggestion.

You can enable it with `[p]redditpost publish`

**Comment by tigattack** [comment]
Thanks!
