### ISSUE TITLE
[Redditpost] Embeded message stop working

### ISSUE THREAD

**Issue by SteevFR** [flaree/flare-cogs#196]
I had to restart my bot, since this time the embedded message from Redditpost stop working correctly sometimes its here another time its not here, just a source button. I tried to reinstall the cog but it doesnt fix anything.
https://prnt.sc/cHDHyufggeXj

**Comment by flaree** [comment]
What version of Red are you running?

**Comment by SteevFR** [comment]
I'm running Red 3.5.1

**Comment by flaree** [comment]
Well, there's no Source button in this version so try updating to latest.
