### ISSUE TITLE
[FEATURE] [COG] Giveaways multi-role expansion

### ISSUE THREAD

**Issue by Orionahn** [flaree/flare-cogs#199]
**Related to the Giveaways cog:** Allow multiplier/multi-roles to be applied to multiple different roles with different multipliers.

**Additional context**
Currently, from what I've tried; in the Giveaways cog the --multiplier and --multi-roles optional arguments can only apply 1 multiplier to multiple roles. I think it would be useful to have it be able to apply multiple multipliers to multiple roles.

**Comment by flaree** [comment]
to not make it too complex it'll stay as is
