### ISSUE TITLE
Additional modmail settings

### ISSUE THREAD

**Issue by kennnyshiwa** [flaree/Flare-Cogs#2]
Is it possible to have modmail setup so that it responds via a command to forward the message? Currently it seems that modmail is just the forwarder cog with a different name and can forward to a channel. it would be nice if there was a additional settings to allow modmail to only be triggered when the person does !modmail in dms or a channel so that admins/mods dont get bombarded with all of the dms to the bot since some people tend to use dms for other stuff such as payday or other similar commands

**Comment by flaree** [comment]
Forwarding of DMs can now be disabled and can now use [p]modmail to send it manually.
