### ISSUE TITLE
Feature Request: Covid - Additional stats

### ISSUE THREAD

**Issue by evacfk** [flaree/Flare-Cogs#21]
Hi Flare,

I'm currently using another bot to track COVID stats but would prefer to use your cog on my own bot.

The majority of my server is US based, would it be possible to have a breakdown by state? 

Such as: [p]cov region usa ca to list the statistics for California.

A top 10 cities within a region would also be nice.

Thanks.

**Comment by flaree** [comment]
Unfortunately the API I use only gives back the country data and not per state. If you cna find a valid API which returns this data then I can accommodate your request.

**Comment by evacfk** [comment]
Thanks for the quick reply, i'm not familiar with which API they are using.

**Comment by cwh1te** [comment]
There is this API available:
http://covid-19api.com/
but I do not know how often it is updated (the data set it's based on is updated more or less daily)

**Comment by flaree** [comment]
The API has had a state command added since. They've also added provinces which I hope I can have time to implement soon.
