### ISSUE TITLE
[FEATURE] [COG] Send As for EmailVerify

### ISSUE THREAD

**Issue by lisbonjoker** [flaree/flare-cogs#210]
**Describe the feature you'd like**
A way to change how I want the Display Name and From Address on the EmailVerify email, for when there is an alias that we want to use instead of the email used a login. For example:
a@gmail.com but send as b@gmai.com. It's not the login email but an alias which belongs and is allowed to send as from that account.

**Comment by flaree** [comment]
Hi, this cog is provided as is - If you'd like to fontribute it yourself then you're more than welcome but I consider it feature locked

**Comment by lisbonjoker** [comment]
Sad to hear that, but I can try, I think.
