### ISSUE TITLE
[FEATURE] [F1] Add forum channels

### ISSUE THREAD

**Issue by mrPauwHaan** [flaree/flare-cogs#212]
**Describe the feature you'd like**
I would like to add F1 subscribe notifications to forum channels

**Additional context**
Currently, I get the notification that the channel is not found when attempting to link it to a forum channel. However, this would be a nice possibility. Our server has a dedicated forum channel specifically for F1 because not everyone is interested so not everyone wants to receive a message during match day.

**Comment by flaree** [comment]
Added
