### ISSUE TITLE
Palette cog does not work due to error

### ISSUE THREAD

**Issue by searinminecraft** [flaree/flare-cogs#228]
**Describe the bug**

Executing any command from the cog results in this error here in the console:

```
May 10 17:25:52 hostname python[111640]: [2024-05-10 17:25:52] [ERROR] red: Exception in command 'palette'
May 10 17:25:52 hostname python[111640]: Traceback (most recent call last):
May 10 17:25:52 hostname python[111640]:   File "/REDACTED/.venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
May 10 17:25:52 hostname python[111640]:     ret = await coro(*args, **kwargs)
May 10 17:25:52 hostname python[111640]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 10 17:25:52 hostname python[111640]:   File "/REDACTED/.local/share/Red-DiscordBot/data/REDACTED/cogs/CogManager/cogs/palette/palette.py", line 72, in palette
May 10 17:25:52 hostname python[111640]:     image = await self.create_palette(img, amount, False, sorted)
May 10 17:25:52 hostname python[111640]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 10 17:25:52 hostname python[111640]:   File "/REDACTED/.local/share/Red-DiscordBot/data/REDACTED/cogs/CogManager/cogs/palette/palette.py", line 125, in create_>
May 10 17:25:52 hostname python[111640]:     final = final.resize((500 * len(colors), 500), resample=Image.ANTIALIAS)
May 10 17:32:51 hostname python[111640]: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Output of [p]help CogName and [p]debuginfo**

This is a collection of commands that are used to show colour palettes.
Cog version: 0.0.2
Author: flare(flare#0001)

<hr>

# Debug Info for Red:

## System Metadata:
CPU Cores: 4 (x86_64)
RAM: 1.4GB/3.7GB (45.1%)

## OS variables:
OS version: Manjaro Linux 23.1.4
User: REDACTED
Python executable: /REDACTED/Bots/REDACTED/.venv/bin/python
Python version: 3.11.8 (64bit)
Pip version: 24.0
Red version: 3.5.9
Discord.py version: 2.3.2

## Red variables:
Instance name: REDACTED
Command line arguments: ['/REDACTED/.venv/bin/python', '-O', '-m', 'redbot', 'REDACTED', '--no-prompt']
Global prefix(es): '='
Owner(s): REDACTED
Disabled intents: None
Storage type: JSON
Data path: /REDACTED/.local/share/Red-DiscordBot/data/REDACTED
Metadata file: /REDACTED/.config/Red-DiscordBot/config.json

**Comment by flaree** [comment]
This should be fixed now.
