### ISSUE TITLE
[Unbelievaboat] Option to set max amount of money you can keep in the wallet

### ISSUE THREAD

**Issue by jack1142** [flaree/Flare-Cogs#25]
This would be good for economy of cogs that use Red's Bank - for example - it could prevent people from putting all their money into the wallet before doing a rebirth in Adventure cog.

I think making it just so that you can't withdraw more money from the bank but still can get money from other unbelievaboat's sources if you reached max amount would be okay but you could just as well prevent getting any money into the wallet once max is reached, it would probably require you to make more changes though.

**Comment by jack1142** [comment]
Wait... Only money form Unbelievaboat goes into the wallet, right? 🤦

**Comment by jack1142** [comment]
No, I'm wrong again

**Comment by flaree** [comment]
Added the ability to set a maximum amount for the wallet in fabd220d494827b02ebc9ef0b5a348001609ed4c. Once it's reached, no more can be added. Each prompt now says if the wallet is full and roulette will only show the winnings that allowed it to be set to the max.
