### ISSUE TITLE
[Unbelievaboat] robing and wallets

### ISSUE THREAD

**Issue by lakai** [flaree/Flare-Cogs#26]
People are robbing, then emptying their wallets so they can not be robbed.   Is there a way to combat this ?  for the time being I set a deposit cooldown to 3 days.

**Comment by flaree** [comment]
I can set a cooldown that can be changed similar to the ones on the work, crime and rob commands to combat this. Would this be helpful?

**Comment by flaree** [comment]
Added optional cooldown to withdraw and deposit, defaults to 1 seconds:
5915b81aeb152462abae941360cd85e9ea5bfcde

**Comment by lakai** [comment]
that works, thanks!

**Comment by dannymichel** [comment]
There is no .rob command

**Comment by dannymichel** [comment]
there is no .slut command

**Comment by flaree** [comment]
> there is no .slut command

This is intentional.
