### ISSUE TITLE
Additional Forwarder settings

### ISSUE THREAD

**Issue by kennnyshiwa** [flaree/Flare-Cogs#3]
It would be neat if forwarder could also forward the dms to the bot to a specific channel, similar to modmail, but more similar to errorlogs, so i one could funnel the bot dms to a specific channel say in another server for review if they dont want to recieve all the pms from the bot with what others are saying, but still want to be able to review them if needed

**Comment by flaree** [comment]
Sorry, I'd rather keep forward how it is as so it doesn't interfere with modmail too much.
