### ISSUE TITLE
[Userinfo] Old adventure cog causes a crash

### ISSUE THREAD

**Issue by aikaterna** [flaree/Flare-Cogs#47]
In the cog server at: https://discordapp.com/channels/240154543684321280/240212783503900673/751453769388130376

An older adventure cog will not have the attribute referred to in https://github.com/flaree/Flare-Cogs/blob/407eb62648205e6f206fbedc47970c7b3fc66ccd/userinfo/userinfo.py#L265

**Comment by flaree** [comment]
Should be fixed in d3089d4

Thanks
