### ISSUE TITLE
[commandstats] add total guild commands

### ISSUE THREAD

**Issue by phenom4n4n** [flaree/Flare-Cogs#54]
Add a command that displays a “leaderboard” of the guilds with most/least commands, with the option to reverse the order it displays in.

**Comment by flaree** [comment]
Just gonna leave this for a few days if anyone would like to get a hacktober PR otherwise I'll start it by end of week

**Comment by xPolar** [comment]
I want to take a jab at it. Are there any resources you'd be able to provide me on the bot's inner workings, such as how it stores when a guild uses a command, and how to connect to the database?

**Comment by flaree** [comment]
Sure, this isn't actually a bot in itself but a cog for [Red-DiscordBot](https://docs.discord.red/en/stable/). It uses Red's built in config system for persistent storage and the correct data should be stored under the guild group for each respective group. Config docs can be found [here](https://docs.discord.red/en/stable/framework_config.html). It's not the simplest of tasks for those who are not familiar with Red or how it operates so if you don't wish to continue it, let me know.

**Comment by flaree** [comment]
added in 2ed22636d0fe37973e20475e0804a08801be4424
