### ISSUE TITLE
[EmbedCreator] Cog Doesn't Support Multi-Embed Messages

### ISSUE THREAD

**Issue by infamous-jacob** [flaree/Flare-Cogs#64]
**Describe the bug**
Attempting to have multiple embeds in the same message outputs an [error](https://i.imgur.com/DlA7Nf2.png). I also found this website where it shows you how to have multiple embeds in the same message: [Discohook.org](https://discohook.org)

**Output of [p]help CogName and [p]debuginfo**
Here is the [[p]help EmbedCreator](https://i.imgur.com/u8fqwzQ.png), and [[p]debuginfo](https://i.imgur.com/2QexK5r.png)

**Comment by flaree** [comment]
Bots don't support multi embeds. They're webhook only.
