### ISSUE TITLE
Feature Request: Highlight global toggle

### ISSUE THREAD

**Issue by Kovaelin** [flaree/Flare-Cogs#7]
Would it be possible to have words be highlighted in all channels, please? Having it as a toggle option would be useful. Thanks.

**Comment by flaree** [comment]
Unfortunately I won't be adding it due to people will be highlighted if mentioned in channels they can't see. I'll think about it but it'll only be if they can see that channel.

**Comment by Kovaelin** [comment]
Would it be possible to add channels through another channel? For example, let's say a server has a dedicated channel for bot commands, then they can add the channel ID to the string.

**Comment by flaree** [comment]
A channel option has been added as of 1.1.0. You can now do [p]highlight add #channel string you want highlighted OR you can use it as [p]highlight add string you want highlighted.
You must have access to the channel to use the toggle command however. If there's anymore suggestions or issues then let me know as I didn't have much time to test.

**Comment by Kovaelin** [comment]
Thanks for adding the feature! One thing that seems to be missing is the ability to toggle new additions from the seperate channel. Thanks again!

**Comment by flaree** [comment]
I'll look into listing them all and read above as to why I didn't enable toggling from another channel.

**Comment by Kovaelin** [comment]
By having "access", do you mean you have permissions or have to be inside the channel? Because I have permissions and still can't use toggle.

**Comment by flaree** [comment]
You must use the command in the channel directly as to avoid those with no access to the channel being able to add and toggle highlights in said channel.
