### ISSUE TITLE
[Suggestion] EmbedCreator | Embed Editmsg

### ISSUE THREAD

**Issue by Menteroth** [flaree/Flare-Cogs#73]
Is `embed editmsg` like Sinbad has in his embed cog something you'd consider? I know changing an embed in a message is a great help when you have a bunch of embeds in an info/rule channel for a server. Reposting them all just to change one message would be quite the hassle. 

Some extra info taken from the old cog.
`Syntax: +embed editmsg <message> <embedname> [use_global=False]`
**Edits an existing message by channelID-messageID to have an embed (must be saved)**

**Comment by flaree** [comment]
Added in a3ea724e884ff8a87d8f01d3a1f7f12a342a7b63
