### ISSUE TITLE
[Suggestion] EmbedCreator | Embed Pages

### ISSUE THREAD

**Issue by Menteroth** [flaree/Flare-Cogs#74]
I have no idea if this is plausible but it would be really cool.

So if you wanted to like create a help with custom commands/aliases or whatever to show.
That might grow into a very long embed when it's posted or perhaps ending up having too many characters for one embed.
My suggestion/question is if it would be possible to have options to decide what text would be on what page of several embeds.

You define how many pages you want it to have. You give it an embed for a specific page. One at a time or something. Like an interactive option like some cogs use. Or whatever works better.

`embed menu <pages>`

After that you get questions to upload an embed for page 1, then page 2 and so on.
Finally when using the command that is aliased to drop page 1, or something just pulling this out of the blue, it will know that this embed has more than one connected to it and will add the left/right arrows to change page and also the crossmark so you can delete if you want.

I hope I didn't leave anything out from my mind to try and explain it. But I think you probably get what I mean.

**Comment by flaree** [comment]
Added in 5e5f8d44775417b516819b894690d5dc8b068c0c
