### ISSUE TITLE
[EmbedCreator] Suggestion | Storing an Embed

### ISSUE THREAD

**Issue by Menteroth** [flaree/Flare-Cogs#75]
It would be nice to also have the option to store an embed from a message directly to an embed instead of JSON file you then need to upload to create the embed.

So like  `embed from <message_id> [channel] [name] [embed|json]` or something similar.
It was very handy in the old cog.

**Comment by flaree** [comment]
Added in 5688052873919daabbd27d489cf8d5dcbd9c7e43
