### ISSUE TITLE
[EmbedCreator] Suggestion | Truncate Lines

### ISSUE THREAD

**Issue by Menteroth** [flaree/Flare-Cogs#77]
```
"flare: help will truncate it to keep it inline, you have to directly invoke. help for that command to see it"
"Menteroth: Flare, That'd be nice with the menu option for your embed cog heh."
```

So yeah. When creating an embed menu it would be nice to have the option to truncate the lines or not to make custom help commands with embeds look better.

**Comment by flaree** [comment]
I don't particularly like this idea, I don't impose any restrictions bar what discord has for limits and I don't do any checking if what's in the embed. If a user wants to mimic the help then they should truncate the text when adding. There's no viable way for me to do so without some botched attempt and forcing people to use a specific way

**Comment by Menteroth** [comment]
You mean like "Blablabla bla..." manually right? I guess that works. No worries either btw. Just thought it'd be a cool thing.
