### ISSUE TITLE
[EmbedCreator] [Suggestion] Other users unable to send saved embeds.

### ISSUE THREAD

**Issue by Lewimaron** [flaree/Flare-Cogs#86]
Hi,
I've created a set of embeds in our server and assigned the [p]embed send commands for each of them to an alias for other users to use. Unfortunately sending of these embeds only works for me. Other users have tried both the aliases and the send embed command directly with no luck.
Is there an option to enable this somewhere in the cog? If not, is it possible to have this added/fixed?

**Comment by flaree** [comment]
Users must be set as bot admin or have the manage channels permission. This is intentional to avoid abuse, if you want to open it up to others then use the inbuilt permissions cog.
