### ISSUE TITLE
[ServerLock] Add A Channel Lock Command

### ISSUE THREAD

**Issue by J-Daniel-1** [flaree/Flare-Cogs#87]
### Feature Request
Add a toggling `[p]lock [channel]` command that restores previous permissions when unlocking a channel. If used the command without specifying a channel, have it lock/unlock in the channel the command was ran in.

**Comment by flaree** [comment]
I suggest using [Sharky's](https://github.com/SharkyTheKing/Sharky) lockdown cog. It offers a lot more functionality and I no longer update mine. It was created for one use case and never had plans on expanding it.
