### ISSUE TITLE
[EmbedCreator] Cog Doesn't Support "Content"

### ISSUE THREAD

**Issue by J-Daniel-1** [flaree/Flare-Cogs#89]
## Feature Request
Add `content` support so we can have messages in addition to the embeds.

Referencing [this discord message](https://canary.discord.com/channels/240154543684321280/736337036067209216/793692899123920916)

**Comment by flaree** [comment]
I'm currently on a small hiatus from my public cogs for the meatime. I will leave this open until I'm back working on my cogs.

**Comment by J-Daniel-1** [comment]
Hey Flare, was wondering if you're back working on your cogs?

**Comment by flaree** [comment]
Not for full feature requests, I'm slowly working on fixing bugs and stuff that I had planned. It'll be gradual fixes for now

**Comment by J-Daniel-1** [comment]
Sounds good. This request isn't in any rush :)

**Comment by flaree** [comment]
Added in e6f20c376d2dd24b6d44294efd9b008eaf6aa559

Let me know if any issues occur, sorry for the wait.
