### ISSUE TITLE
[FACEIT] Issue with first game statistics

### ISSUE THREAD

**Issue by Ufinexa** [flaree/Flare-Cogs#93]
Clicking the medal reaction gives me a console log error that shows this 

![firefox_X8jfatZCQS](https://user-images.githubusercontent.com/46165534/104472032-6eb82180-55b3-11eb-919e-04ce310038e7.png)

**Comment by flaree** [comment]
Fixed in d0abe3e43a6a6907c41f45fd2155235ac010c91b

**Comment by Ufinexa** [comment]
Upon updating to this, I got mostly the same error but with some different lines being the issue.

![firefox_BSbm9RYPIA](https://user-images.githubusercontent.com/46165534/104854397-60913a80-58fe-11eb-9651-9231268bab39.png)

**Comment by flaree** [comment]
What is the faceit name of the profile being looked up?

**Comment by Ufinexa** [comment]
here is the faceit profile https://www.faceit.com/en/players/Ufinexa

**Comment by Ufinexa** [comment]
I assume this would be the first game if this is what it meant https://www.faceit.com/en/csgo/room/1-10297646-7ca1-4b53-a40b-a13847b7fd51/scoreboard

**Comment by flaree** [comment]
should be fixed now

**Comment by Ufinexa** [comment]
Fixed! Thank you so much :)
