### ISSUE TITLE
Join message image 

### ISSUE THREAD

**Issue by Ronish1122** [flaree/Flare-Cogs#96]
Could you possibly make the embed join message support images? Would be great

**Comment by flaree** [comment]
All my cogs are currently feature locked. I will not be adding this unless someone else is willing to. I will leave this issue open in the case anyone sees it and is willing. I have no purpose for embedding it and am against having embeds everywhere.

**Comment by flaree** [comment]
Added in 3d059f9eca738f1d621c8b8cd04817c4464726d4.

No support will be offered for this.
